site_name: 'スターターキット'

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  hljs_languages:
    - yaml
    - dockerfile

extra:
  search:
    language: 'ja'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - 'assets/custom.css'

extra_javascript:
  - 'assets/custom.js'

nav:
  - 'Home': 'index.md'

  - 'はじめに':
      - 'クラウド': '0_introduction/cloud.md'
      - 'コンテナ': '0_introduction/container.md'
      # - 'CI/CD': '0_introduction/ci_cd.md'
      - 'Infrastructure as Code': '0_introduction/iac.md'
      - '監視': '0_introduction/monitoring.md'

  - '構築':
      - '目標の確認': '1_construct/structure.md'
      - 'プロビジョニング': '1_construct/provisinong.md'
      - 'デプロイ': '1_construct/deploy.md'
      # - '4. 監視': ''

  - 'まとめ': 'finally.md'


  # - '実践':
  # - 'まとめ':
